### ISSUE TITLE
Overwriting users vulnerability

### ISSUE THREAD

**Issue by seanmtracey** [Choirless/choirlessapi#15]
The create + update user endpoints seem to use the same code.

As far as I can see from the docs, there's no way from an application side (the Choirless application server, for example) to check if a user is trying to create an account with details (email address) that we already have in our database, creating the possibility that someone could fairly easily steal an account by inputting someone else's email and a new password.

I think we should break up the `POST /user` route into two separate endpoints 
- `POST /user/create` which checks to make sure there isn't an account already in existence.
- `POST /user/update` which can update user details (provided they've passed a challenge set by the application server or similar)

**Comment by glynnbird** [comment]
All the API endpoints are like that. If you omit the Id you get a new doc,
if you provide one it does an update.

**Comment by seanmtracey** [comment]
Ah, ok! So, if someone signs up with an email address, but then someone else signs up with the same email address, there'd be two users, but with the same email address?

**Comment by glynnbird** [comment]
I don't mind making the change but the existing API makes it easy to
differentiate an insert from an update , whether it's
song/choir/user/songpart.

If they must be separated, we could use PUT to mean insert and POST to mean
update?

**Comment by seanmtracey** [comment]
I agree, I think the API is wonderfully clear and concise, but I worry about the user endpoints being an attack vector if the account creation is an implicit action instead of an explicit one.

Different HTTP verbs makes sense, and I'm more than happy to put in a PR if you're happy for me to submit one :)

**Comment by glynnbird** [comment]
Leave me something to do @seanmtracey ;) I'll do the POST / PUT thing.

I think we also need an API call that allows a user doc to be fetched by email address - that way your app can detect if a user (with that email address) already exists. There's no constraint in the API (or the database for that matter) to prevent two users being created with the same email address.

**Comment by seanmtracey** [comment]
😂I just love putting in PRs!

Having an endpoint that lets applications find a user by email could be super handy 👍 

Just thinking, rather than splitting out the endpoint into two parts, what if the one endpoint does a check for a user with the same email before allowing the creation of a new account? It's an extra database read, but it would solve the problem and we could keep the one endpoint. If an existing user is found with the same email as the one being requested, we could just output something like "that address already has an account" which the API consumer can then decide how to handle.

**Comment by glynnbird** [comment]
That's a better idea. Http 409 when duplicate user detected.

**Comment by glynnbird** [comment]
PR merged #16
