### ISSUE TITLE
List + revoke beta invitations

### ISSUE THREAD

**Issue by seanmtracey** [Choirless/choirlessapi#36]
It would be handy for the admin section of the front end to have an endpoint it could use to revoke and list all of the invitations sent out to beta users.

Suggested endpoints:

GET `/invitation/list-all`
DELETE `/invitation?inviteId=<INVITE_ID>`

**Comment by glynnbird** [comment]
No problem.

Can I suggest:

## GET /invitation/list

Fetch all invitations _that haven't already expired_.

Parameters: none

## DELETE /invitation

Delete an existing invitation.

Parameters

- `inviteId` - the invitation to delete

**Comment by seanmtracey** [comment]
Looks great :)

**Comment by seanmtracey** [comment]
Actually, an extra thought: would it be possible to have something like `?created by=USERID` as an optional parameter so I don't have to filter it on my side?
